// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rivo/tview"
)

// Injectors from wire.go:

func InitializeRootApp() (ExecuteAble, error) {
	logrusLogger := NewLogger()
	viper := NewViper()
	application := tview.NewApplication()
	executeAble := NewApp(logrusLogger, viper, application)
	return executeAble, nil
}
