// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

// Injectors from wire.go:

func InitializeRootApp() (ExecuteAble, error) {
	logrusLogger := NewLogger()
	viper := NewViper()
	executeAble := NewApp(logrusLogger, viper)
	return executeAble, nil
}
