// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/jneo8/jujuspell/common"
	"github.com/jneo8/jujuspell/jujuclient"
)

// Injectors from wire.go:

func InitializeRootApp() (ExecuteAble, error) {
	logger := common.NewLogger()
	viper := common.NewViper()
	jujuClient, err := jujuclient.InitializeJujuClient()
	if err != nil {
		return nil, err
	}
	executeAble := NewApp(logger, viper, jujuClient)
	return executeAble, nil
}
