// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package jujuclient

import (
	"github.com/jneo8/jujuspell/common"
	"github.com/juju/juju/jujuclient"
)

// Injectors from wire.go:

func InitializeJujuClient() (JujuClient, error) {
	clientStore := jujuclient.NewFileClientStore()
	logger := common.NewLogger()
	jujuclientJujuClient, err := NewJujuClient(clientStore, logger)
	if err != nil {
		return nil, err
	}
	return jujuclientJujuClient, nil
}
